# Nick Adams 00883496

## You are allowed and encouraged to search and get help from any resource, but write down the code by your own hands. 

In [1]:
import numpy as np

### Your work: 

Create a new cell right below this cell. In the new cell, write one or a few statements that create and print a $3 \times 4$ (ie., 3 rows by 4 columns)  ndarray of random numbers from the range $[0,1)$. The result should be something similar to the following (numbers could be different): 

[[0.21559175 0.71091185 0.78264013 0.0816029 ]

 [0.86528926 0.43816422 0.9406306  0.54750664]

[0.794279   0.48067576 0.97565906 0.72432521]]

In [2]:
a1 = np.random.random((3,4))
print(a1)

[[0.33981724 0.91378195 0.95568813 0.78643472]
 [0.6790687  0.43183517 0.36313438 0.43753702]
 [0.34680575 0.97674192 0.8989216  0.45048166]]


In [3]:
a = np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


### Your work:
Creat a new cell right below this cell. In the new cell, write one or a few statements that print the transpose of matrix $a$ defined above. The print should be looking like this: 

[[1 4]

 [2 5]

[3 6]]

In [4]:
b1 = a1.transpose()
print(b1)

[[0.33981724 0.6790687  0.34680575]
 [0.91378195 0.43183517 0.97674192]
 [0.95568813 0.36313438 0.8989216 ]
 [0.78643472 0.43753702 0.45048166]]


In [5]:
b = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


### Your work:
Creat a new cell right below this cell. In the new cell, write one or a few statements that print the multiplication of matrix a and matrix b that are definded above. The print should be looking like this: 

[[ 38  44  50  56]

 [ 83  98 113 128]]


In [6]:
c1 = a1@b1
print(c1)

[[2.48229256 1.31649995 2.22374282]
 [1.31649995 0.97092114 1.18082818]
 [2.22374282 1.18082818 2.08529277]]


In [7]:
c = np.array([[10,20,30],[40,50,60]])
print(c)

[[10 20 30]
 [40 50 60]]


### Your work:
Creat a new cell right below this cell. In the new cell, write one or a few statements that print the element-wise (also called component-wise) multiplication of matrix a and matrix c that definded above. The print should be looking like this: 

[[ 10  40  90]

 [160 250 360]]

In [8]:
res = np.multiply(a,c)
print(res)

[[ 10  40  90]
 [160 250 360]]


### Your work:

Creat a new cell right below this cell. In the new cell, write one or a few statements that add a new column to matrix b (the newly added column becomes the 0th column), and save the resuling new matrix to d (without changing b), then print d. The print should be looking like this: 

[[ 1  1  2  3  4]

 [ 1  5  6  7  8]

[ 1  9 10 11 12]]

Hint: Use np.insert() method. Search and read its document. 

In [9]:
d = np.insert(b, 0, 1, axis=1)
print(d)

[[ 1  1  2  3  4]
 [ 1  5  6  7  8]
 [ 1  9 10 11 12]]


In [10]:
e = np.array([1,2,3])
print(e)

[1 2 3]


### Your work:

Creat a new cell right below this cell. In the new cell, write one or a few statements that prints the inverse of e. The result should be the following: 

    [[1]

     [2]

    [3]]

Hint: Study the reshape function. You need to increase the ndim of the ndarray from 1 to 2, then the transpose function can work. 

In [15]:
print(e.reshape(1,3).transpose())

[[1]
 [2]
 [3]]
